export const SWAGR_PROMO_FACTS = [
  {
    id: 'market-2025-sales',
    category: 'Market',
    signal: '$27.7B',
    headline: 'North American promo distributor sales reached a record high in 2025.',
    detail: 'ASI reported $27.7 billion in 2025 North American promotional-products distributor sales, up 4.2% from 2024.',
    planningSignal: 'The channel is large and still growing, but this is industry-scale context—not proof of demand for a specific product, account, or campaign.',
    source: {
      publisher: 'Advertising Specialty Institute (ASI)',
      title: 'North American Promotional Products Industry Grows 4.2% in 2025 to Record $27.7 Billion',
      published: 'January 21, 2026',
      url: 'https://asicentral.com/press-releases/north-america-promo-industry-grows-4-percent-in-2025/',
      method: 'ASI annual distributor sales research',
    },
  },
  {
    id: 'market-q4-2025',
    category: 'Market',
    signal: '+5.1%',
    headline: 'The industry finished 2025 with its strongest quarter of the year.',
    detail: 'ASI reported Q4 2025 distributor sales were 5.1% higher than Q4 2024.',
    planningSignal: 'Treat this as a dated market pulse. It can inform timing conversations, but it does not replace current supplier, buyer, or category data.',
    source: {
      publisher: 'Advertising Specialty Institute (ASI)',
      title: 'North American Promotional Products Industry Grows 4.2% in 2025 to Record $27.7 Billion',
      published: 'January 21, 2026',
      url: 'https://asicentral.com/press-releases/north-america-promo-industry-grows-4-percent-in-2025/',
      method: 'ASI annual distributor sales research',
    },
  },
  {
    id: 'retention-usefulness-2025',
    category: 'Retention',
    signal: '57%',
    headline: 'Usefulness remains a strong reason people keep branded merchandise.',
    detail: 'In PPAI Research’s 2025 consumer study, 57% of respondents said they kept the most recent promotional product they received because it was useful in daily life.',
    planningSignal: 'Utility is a meaningful selection signal. SWAGR can weight practical fit, but it should not assume every “useful” category will work for every audience.',
    source: {
      publisher: 'Promotional Products Association International (PPAI)',
      title: 'PPAI Research: The 5-Second Impact',
      published: 'October 3, 2025',
      url: 'https://www.ppai.org/media-hub/ppai-research-the-5-second-impact/',
      method: 'Online survey of 1,000 U.S. consumers',
    },
  },
  {
    id: 'quality-look-feel-2025',
    category: 'Quality',
    signal: '42%',
    headline: 'Look and feel influence whether a promo item earns a place in someone’s life.',
    detail: 'In the same PPAI study, 42% said they kept their most recent promo product because it looked good and felt high-quality.',
    planningSignal: 'Perceived quality and visual design deserve explicit weight in product ranking—not just unit price.',
    source: {
      publisher: 'Promotional Products Association International (PPAI)',
      title: 'PPAI Research: The 5-Second Impact',
      published: 'October 3, 2025',
      url: 'https://www.ppai.org/media-hub/ppai-research-the-5-second-impact/',
      method: 'Online survey of 1,000 U.S. consumers',
    },
  },
  {
    id: 'quality-rejection-2025',
    category: 'Quality',
    signal: '>60%',
    headline: 'Poor material or construction can create an immediate negative reaction.',
    detail: 'PPAI reported that more than 60% of respondents were immediately turned away by poor material or construction; 38% cited boring or generic design and 37% cited already having too many similar items.',
    planningSignal: 'Cheap-feeling execution is a brand risk. SWAGR should surface quality, originality, and audience saturation as planning checks before chasing the lowest apparent cost.',
    source: {
      publisher: 'Promotional Products Association International (PPAI)',
      title: 'PPAI Research: The 5-Second Impact',
      published: 'October 3, 2025',
      url: 'https://www.ppai.org/media-hub/ppai-research-the-5-second-impact/',
      method: 'Online survey of 1,000 U.S. consumers',
    },
  },
  {
    id: 'brand-action-2025',
    category: 'Behavior',
    signal: '76% / 72%',
    headline: 'Recipients in PPAI’s 2025 study reported brand research and purchase behavior after receiving promo.',
    detail: 'In the survey, 76% said they had looked up the brand of a promo item they received, and 72% said they had made a purchase from a brand because of a promotional product they received.',
    planningSignal: 'This is self-reported survey behavior, not a guaranteed causal lift. Use it to support thoughtful campaign design—not outcome promises.',
    source: {
      publisher: 'Promotional Products Association International (PPAI)',
      title: 'PPAI Research: The 5-Second Impact',
      published: 'October 3, 2025',
      url: 'https://www.ppai.org/media-hub/ppai-research-the-5-second-impact/',
      method: 'Online survey of 1,000 U.S. consumers',
    },
  },
  {
    id: 'audience-apparel-2025',
    category: 'Audience',
    signal: '#1',
    headline: 'Apparel ranked first across Gen Z, Millennials, and Gen X in a 2025 PPAI preference study.',
    detail: 'PPAI Research surveyed more than 3,000 U.S. consumers ages 16–60 and reported apparel as the top promotional-product category across the generations studied.',
    planningSignal: 'A broad preference is a useful starting point, not a default answer. Audience, use case, sizing, distribution friction, climate, and brand fit still matter.',
    source: {
      publisher: 'Promotional Products Association International (PPAI)',
      title: 'Top Promo Categories By Generation: Infographic',
      published: 'September 29, 2025',
      url: 'https://www.ppai.org/media-hub/top-promo-categories-by-generation-infographic/',
      method: 'Survey of more than 3,000 U.S. consumers ages 16–60',
    },
  },
  {
    id: 'retention-five-years-2021',
    category: 'Retention',
    signal: '48.7%',
    headline: 'Nearly half of respondents in an earlier PPAI study said they kept promo products for more than five years.',
    detail: 'PPAI’s consumer research with 5,674 end users in the U.S. and Canada found 48.7% kept promotional products longer than five years; 75.4% cited usefulness as a reason for keeping them.',
    planningSignal: 'Long retention can make the right item valuable over time. The data is older, so SWAGR labels it clearly instead of presenting it as a current-year benchmark.',
    source: {
      publisher: 'Promotional Products Association International (PPAI)',
      title: 'New PPAI Research Shows Why Consumers Take And Keep Promo Products',
      published: '2021',
      url: 'https://www.ppai.org/media-hub/new-ppai-research-shows-why-consumers-take-and-keep-promo-products/',
      method: 'Survey of 5,674 end users in the U.S. and Canada',
    },
  },
  {
    id: 'sustainability-carbon-2026',
    category: 'Sustainability',
    signal: '8× lower',
    headline: 'A 2026 commissioned study reported lower carbon impact per memorized impression for promo than digital advertising.',
    detail: 'PPAI and ASI reported that an independent study they commissioned found promotional products had eight times lower carbon impact per memorized impression than digital advertising.',
    planningSignal: 'This is a channel-level study result, not a claim that every physical product is sustainable. Material, manufacturing, freight, longevity, and disposal still need item-level scrutiny.',
    source: {
      publisher: 'PPAI / ASI',
      title: 'Joint PPAI-ASI Study Finds Promo Among The Lowest Carbon Impact Advertising Channels',
      published: 'February 4, 2026',
      url: 'https://www.ppai.org/media-hub/joint-ppai-asi-study-finds-promo-among-the-lowest-carbon-impact-advertising-channels/',
      method: 'Independent study commissioned by PPAI, ASI, and European promo partners',
    },
  },
];

export const SWAGR_PROMO_FACT_CATEGORIES = [
  'All',
  ...Array.from(new Set(SWAGR_PROMO_FACTS.map((fact) => fact.category))),
];

export const SWAGR_PROMO_FACT_META = {
  verifiedThrough: 'September 4, 2026',
  runtimeMode: 'STATIC_SOURCE_LABELED_LIBRARY',
  truthBoundary: 'Research context only. No live price, inventory, supplier approval, product performance, campaign outcome, quote, order, proof, or production authority.',
};
