export const SWAGR_FIXTURES = [
  {
    id: 'SWAGR-CAT-001',
    name: 'Decorated Short-Sleeve Tee Concept',
    category: 'Apparel — knit tops',
    audiences: ['event attendees', 'volunteers', 'frontline teams', 'campus groups'],
    useCases: ['event', 'program', 'team', 'recruiting'],
    quantities: ['QTY_MID', 'QTY_LARGE'],
    budgets: ['BAND_GIVEAWAY', 'BAND_STANDARD'],
    rationale: 'A broad-utility identity item for larger audiences and recurring programs. It is a useful starting concept when reach and group identity matter more than premium gifting.',
    decoration: ['Screen print', 'Heat transfer', 'Small-placement embroidery'],
    creative: 'Use a strong front or back graphic with a simplified left-chest mark. Product-level decoration feasibility still requires validation.',
    evidence: 'FICTIONAL_CONCEPT + PUBLIC_SOURCE_CATEGORY_CONTEXT',
    cautions: ['No price or stock claim', 'No guaranteed delivery', 'No fabric-performance claim', 'Decoration requires validation'],
  },
  {
    id: 'SWAGR-CAT-002',
    name: 'Mid-Layer Fleece / Outerwear Concept',
    category: 'Apparel — outerwear / mid-layer',
    audiences: ['employees', 'VIP recipients', 'executive gifting', 'field crews'],
    useCases: ['recognition', 'gifting', 'employee', 'field'],
    quantities: ['QTY_SMALL', 'QTY_MID'],
    budgets: ['BAND_PREMIUM'],
    rationale: 'A higher-perceived-value wearable suited to recognition and gifting when repeat use matters more than broad distribution.',
    decoration: ['Embroidery', 'Applique', 'Patch application'],
    creative: 'Favor a restrained chest or sleeve application and let the garment carry the premium feel. Product-level decoration feasibility still requires validation.',
    evidence: 'FICTIONAL_CONCEPT + INFERENCE',
    cautions: ['No warmth or weather rating', 'No size-run claim', 'No brand substitution claim', 'Decoration requires validation'],
  },
  {
    id: 'SWAGR-CAT-003',
    name: 'Structured Cap / Headwear Concept',
    category: 'Headwear',
    audiences: ['field crews', 'event staff', 'fan audiences', 'community groups'],
    useCases: ['field', 'event', 'team', 'community'],
    quantities: ['QTY_SMALL', 'QTY_MID'],
    budgets: ['BAND_STANDARD'],
    rationale: 'A one-size-forgiving identity item that avoids much of the apparel size complexity while still giving the brand a visible everyday placement.',
    decoration: ['Front-panel embroidery', 'Patch application', 'Rope / visor detail'],
    creative: 'Use a simplified front-panel logo lockup. Detailed marks may need a reduced version before embroidery can be validated.',
    evidence: 'FICTIONAL_CONCEPT + INFERENCE',
    cautions: ['No fit guarantee', 'No stitch-count guarantee', 'No licensed association', 'Decoration requires validation'],
  },
  {
    id: 'SWAGR-CAT-004',
    name: 'Insulated Drinkware Concept',
    category: 'Drinkware',
    audiences: ['employees', 'event attendees', 'wellness participants', 'clients'],
    useCases: ['employee', 'event', 'wellness', 'gifting'],
    quantities: ['QTY_SMALL', 'QTY_MID', 'QTY_LARGE'],
    budgets: ['BAND_STANDARD', 'BAND_PREMIUM'],
    rationale: 'A daily-use category that can fit employee, event, or gifting programs, but it should be chosen for the stated use case rather than treated as an automatic default.',
    decoration: ['Laser engrave', 'Pad print', 'Wrap print'],
    creative: 'Keep the application clean and vertically balanced. Product geometry and exact imprint area require later validation.',
    evidence: 'FICTIONAL_CONCEPT + PUBLIC_SOURCE_CATEGORY_CONTEXT',
    cautions: ['No temperature-retention claim', 'No food-safety certification claim', 'No stock or lead-time claim', 'Decoration requires validation'],
  },
  {
    id: 'SWAGR-CAT-005',
    name: 'Canvas Tote / Carry Concept',
    category: 'Bags — totes and carry',
    audiences: ['conference attendees', 'retail audiences', 'campus groups', 'event attendees'],
    useCases: ['conference', 'event', 'kit', 'campus'],
    quantities: ['QTY_MID', 'QTY_LARGE'],
    budgets: ['BAND_GIVEAWAY', 'BAND_STANDARD'],
    rationale: 'A forgiving large imprint area and useful secondary role as a kit container make this strong when the real job is carrying materials or bundling multiple items.',
    decoration: ['Screen print', 'Large-panel transfer', 'Embroidery patch'],
    creative: 'Use the broad panel for the primary brand moment; if it becomes a kit container, coordinate the outer graphic with the items inside.',
    evidence: 'FICTIONAL_CONCEPT + INFERENCE',
    cautions: ['No load-capacity claim', 'No recycled-content claim', 'No durability rating', 'Decoration requires validation'],
  },
  {
    id: 'SWAGR-CAT-006',
    name: 'Writing Instrument Concept',
    category: 'Writing instruments',
    audiences: ['trade-show traffic', 'office audiences', 'education groups'],
    useCases: ['trade show', 'office', 'education', 'giveaway'],
    quantities: ['QTY_LARGE'],
    budgets: ['BAND_GIVEAWAY'],
    rationale: 'A low-friction broad-distribution concept for high-volume traffic, especially when the goal is reach rather than a premium keepsake.',
    decoration: ['Barrel pad print', 'Metal-barrel laser engrave'],
    creative: 'Use a short, simplified mark that remains legible on a narrow curved barrel. Exact imprint geometry requires product validation.',
    evidence: 'FICTIONAL_CONCEPT + PUBLIC_SOURCE_CATEGORY_CONTEXT',
    cautions: ['No MOQ claim', 'No price claim', 'No writing-performance claim', 'Decoration requires validation'],
  },
];

export const QTY_OPTIONS = [
  ['QTY_UNSTATED', 'Not sure yet'],
  ['QTY_SMALL', 'Small batch'],
  ['QTY_MID', 'Program scale'],
  ['QTY_LARGE', 'Broad distribution'],
];

export const BUDGET_OPTIONS = [
  ['UNSTATED', 'Not sure yet'],
  ['BAND_GIVEAWAY', 'Broad-distribution tier'],
  ['BAND_STANDARD', 'Everyday-program tier'],
  ['BAND_PREMIUM', 'Higher-perceived-value tier'],
];

export const truthLabel = 'Fixture concept — commercial validation required';
