'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, Circle, Link2, RotateCcw, Save, ShieldCheck, TriangleAlert } from 'lucide-react';
import ConceptVisual from '../../concept-visual';
import { SWAGR_GOVERNED_CONCEPTS } from '../../coverage/catalog';
import { PROVIDER_PROJECTION_SCENARIOS, buildSyntheticProviderEnvelope, projectReadOnlyProviderRecord } from '../../data/provider-projection';
import { clearImprintSpec, controlledTemplateForConcept, loadImprintSpec, saveImprintSpec } from '../imprint-readiness';
import { evaluateProductSpecBinding } from '../product-spec-binding';

const C = { bg:'#120D1A', panel:'#1B1530', panel2:'#211938', purple:'#6C47FF', purpleLt:'#B6A6FF', gold:'#F5C842', cream:'#F1EAD8', green:'#34D399', muted:'#AAA0B8', line:'#352A46' };
const inputStyle = { borderColor:C.line, background:'#151020', color:C.cream, outlineColor:C.purple };

function Pill({ children, tone='neutral' }) {
  const tones = {
    neutral:{ color:C.cream, borderColor:C.line, background:'#191225' },
    good:{ color:C.green, borderColor:`${C.green}55`, background:`${C.green}12` },
    warn:{ color:C.gold, borderColor:`${C.gold}55`, background:`${C.gold}12` },
    purple:{ color:C.purpleLt, borderColor:`${C.purple}66`, background:`${C.purple}16` },
  };
  return <span className="inline-flex rounded-full border px-2.5 py-1 text-[10px] font-black uppercase tracking-[0.12em]" style={tones[tone]}>{children}</span>;
}

function Field({ label, note, children }) {
  return <label className="block"><span className="text-xs font-black" style={{color:C.cream}}>{label}</span>{note&&<span className="mt-1 block text-[10px] leading-4" style={{color:C.muted}}>{note}</span>}<span className="mt-2 block">{children}</span></label>;
}

function Gate({ label, pass, detail }) {
  return <div className="rounded-2xl border p-3" style={{borderColor:pass?`${C.green}44`:`${C.gold}55`,background:pass?`${C.green}08`:`${C.gold}08`}}><div className="flex items-center gap-2">{pass?<CheckCircle2 className="h-4 w-4" style={{color:C.green}}/>:<Circle className="h-4 w-4" style={{color:C.gold}}/>}<span className="text-[10px] font-black uppercase tracking-[0.12em]" style={{color:pass?C.green:C.gold}}>{label}</span></div><div className="mt-1 break-words text-xs font-bold" style={{color:C.cream}}>{detail}</div></div>;
}

export default function SwagrProductSpecReadiness() {
  const [conceptId,setConceptId]=useState(SWAGR_GOVERNED_CONCEPTS[3]?.id||SWAGR_GOVERNED_CONCEPTS[0]?.id||'');
  const [scenarioId,setScenarioId]=useState('CONTROLLED_FRESH_SIMULATION');
  const [spec,setSpec]=useState(null);
  const [message,setMessage]=useState('');

  const concept=useMemo(()=>SWAGR_GOVERNED_CONCEPTS.find((x)=>x.id===conceptId)||SWAGR_GOVERNED_CONCEPTS[0],[conceptId]);
  const template=useMemo(()=>controlledTemplateForConcept(concept),[concept]);
  const envelope=useMemo(()=>buildSyntheticProviderEnvelope(concept,scenarioId),[concept,scenarioId]);
  const providerResult=useMemo(()=>projectReadOnlyProviderRecord(concept,envelope),[concept,envelope]);
  const binding=useMemo(()=>evaluateProductSpecBinding(providerResult,spec||{}),[providerResult,spec]);

  useEffect(()=>{const p=new URLSearchParams(window.location.search);const c=p.get('concept');const s=p.get('scenario');if(c&&SWAGR_GOVERNED_CONCEPTS.some((x)=>x.id===c))setConceptId(c);if(s&&PROVIDER_PROJECTION_SCENARIOS.some((x)=>x.id===s))setScenarioId(s);},[]);
  useEffect(()=>{if(concept){setSpec(loadImprintSpec(concept));setMessage('');}},[concept]);
  if(!concept||!spec)return null;

  const projection=providerResult.projection;
  const update=(field,value)=>setSpec((cur)=>({...cur,[field]:value}));
  const bindIdentity=()=>{if(!projection){setMessage('Provider projection is withheld. Resolve the provider gate first.');return;}const next=saveImprintSpec(concept,{...spec,productRef:projection.providerRecordId,sourceLabel:projection.provider,sourceDate:projection.sourceRevision});setSpec(next);setMessage('Eligible simulated provider identity bound to this session-local declaration. No live data was fetched or written.');};
  const save=()=>{setSpec(saveImprintSpec(concept,spec));setMessage('Declaration saved in this browser session only. Nothing was sent externally.');};
  const reset=()=>{setSpec(clearImprintSpec(concept));setMessage('Session-local product/imprint declaration cleared.');};
  const area=Number(spec.imprintWidth),art=Number(spec.artworkWidth);const markScale=Number.isFinite(area)&&area>0&&Number.isFinite(art)&&art>0?Math.min(1.35,Math.max(.65,art/area)):1;
  const tone=binding.status==='PRODUCT_SPEC_READY_FOR_HUMAN_VALIDATION'?'good':'warn';

  return <main className="min-h-screen" style={{background:C.bg,color:'#fff'}}>
    <div className="pointer-events-none fixed inset-0" aria-hidden="true" style={{background:'radial-gradient(56% 42% at 92% 0%, rgba(108,71,255,.24), transparent 72%), radial-gradient(42% 32% at 0% 22%, rgba(245,200,66,.08), transparent 75%)'}}/>
    <header className="relative border-b" style={{borderColor:C.line,background:'rgba(18,13,26,.96)'}}><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-5 py-5"><div className="flex items-start gap-3"><Link href="/swagr/data" aria-label="Back to provider projection gate" className="flex h-10 w-10 items-center justify-center rounded-2xl border focus:outline-none focus:ring-2" style={{borderColor:C.line,color:C.cream,'--tw-ring-color':C.purple}}><ArrowLeft className="h-4 w-4"/></Link><div><div className="flex flex-wrap items-center gap-2"><span className="text-xl font-black">SWAGR AI</span><Pill tone="purple">Product-Specific Virtual Readiness</Pill></div><p className="mt-1 max-w-3xl text-xs leading-5" style={{color:C.muted}}>Bind an eligible read-only product projection to a controlled imprint declaration and expose every remaining validation gap.</p></div></div><div className="flex flex-wrap gap-2"><Pill tone="good">Read only</Pill><Pill tone="warn">Simulation only</Pill><Pill>Non-production</Pill></div></div></header>

    <div className="relative mx-auto max-w-7xl px-5 py-8">
      <section className="mb-6 rounded-3xl border p-5" style={{borderColor:`${C.gold}55`,background:'linear-gradient(135deg, rgba(245,200,66,.08), rgba(27,21,48,.94))'}}><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5" style={{color:C.gold}}/><div><div className="text-sm font-black" style={{color:C.gold}}>Exact product identity + declared imprint spec still does not equal a production proof.</div><p className="mt-1 text-xs leading-5" style={{color:C.muted}}>A green result means ready for human validation only. Price, inventory, MOQ, lead time, supplier approval, artwork approval, proof approval, ordering and production authority remain outside this packet.</p></div></div></section>

      <section className="grid gap-6 xl:grid-cols-[310px_1fr_360px]">
        <aside className="space-y-5">
          <section className="rounded-3xl border p-5" style={{background:C.panel,borderColor:C.line}}><h2 className="text-sm font-black">Controlled product source</h2><label className="mt-4 block text-xs font-bold" style={{color:C.cream}}>Governed concept<select value={conceptId} onChange={(e)=>setConceptId(e.target.value)} className="mt-2 w-full rounded-xl border px-3 py-2.5 text-xs" style={inputStyle}>{SWAGR_GOVERNED_CONCEPTS.map((x)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="mt-4 block text-xs font-bold" style={{color:C.cream}}>Provider scenario<select value={scenarioId} onChange={(e)=>setScenarioId(e.target.value)} className="mt-2 w-full rounded-xl border px-3 py-2.5 text-xs" style={inputStyle}>{PROVIDER_PROJECTION_SCENARIOS.map((x)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><div className="mt-4 rounded-2xl border p-3" style={{borderColor:C.line,background:C.panel2}}><div className="flex flex-wrap gap-2"><Pill tone={binding.checks.providerEligible?'good':'warn'}>{providerResult.evaluation.status}</Pill><Pill>{providerResult.evaluation.score}% gate</Pill></div>{projection?<div className="mt-3 space-y-1 text-[11px] leading-4" style={{color:C.muted}}><div><b style={{color:C.cream}}>Record:</b> {projection.providerRecordId}</div><div><b style={{color:C.cream}}>Revision:</b> {projection.sourceRevision}</div><div><b style={{color:C.cream}}>Usage:</b> {projection.usageRightsState}</div></div>:<p className="mt-3 text-[11px] leading-4" style={{color:C.muted}}>Projection withheld; product identity cannot move forward.</p>}</div><button type="button" onClick={bindIdentity} disabled={!projection} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl px-3.5 py-2.5 text-xs font-black disabled:opacity-45" style={{background:projection?C.purple:'#30283B',color:'#fff'}}><Link2 className="h-4 w-4"/>Bind governed identity</button></section>
          <section className="rounded-3xl border p-5" style={{background:C.panel,borderColor:C.line}}><div className="flex flex-wrap gap-2"><Pill tone="warn">{template.sourceState}</Pill><Pill>{template.templateId}</Pill></div><p className="mt-3 text-xs font-black" style={{color:C.cream}}>{template.label}</p><div className="mt-3 space-y-2">{template.criticalChecks.map((x)=><div key={x} className="text-[10px] leading-4" style={{color:C.muted}}>• {x}</div>)}</div></section>
        </aside>

        <section className="space-y-5">
          <section className="rounded-3xl border p-5 sm:p-6" style={{background:C.panel,borderColor:C.line}}><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-[.14em]" style={{color:C.purpleLt}}>Binding workspace</div><h1 className="mt-1 text-xl font-black">Product identity → controlled imprint spec</h1></div><Pill tone={tone}>{binding.score}% combined</Pill></div>
            <div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Exact product reference" note="Must match the eligible provider projection exactly."><input value={spec.productRef} onChange={(e)=>update('productRef',e.target.value)} className="w-full rounded-xl border px-3 py-2.5 text-xs" style={inputStyle}/></Field><Field label="Controlled source identity" note="Must match the provider identity exactly."><input value={spec.sourceLabel} onChange={(e)=>update('sourceLabel',e.target.value)} className="w-full rounded-xl border px-3 py-2.5 text-xs" style={inputStyle}/></Field><Field label="Source revision"><input value={spec.sourceDate} onChange={(e)=>update('sourceDate',e.target.value)} className="w-full rounded-xl border px-3 py-2.5 text-xs" style={inputStyle}/></Field><Field label="Named imprint placement" note={`Examples: ${template.placementExamples.join(', ')}.`}><input value={spec.placement} onChange={(e)=>update('placement',e.target.value)} className="w-full rounded-xl border px-3 py-2.5 text-xs" style={inputStyle}/></Field></div>
            <div className="mt-4 grid gap-4 sm:grid-cols-[1fr_1fr_100px]"><Field label="Imprint width"><input type="number" min="0" step="0.01" value={spec.imprintWidth} onChange={(e)=>update('imprintWidth',e.target.value)} className="w-full rounded-xl border px-3 py-2.5 text-xs" style={inputStyle}/></Field><Field label="Imprint height"><input type="number" min="0" step="0.01" value={spec.imprintHeight} onChange={(e)=>update('imprintHeight',e.target.value)} className="w-full rounded-xl border px-3 py-2.5 text-xs" style={inputStyle}/></Field><Field label="Unit"><select value={spec.unit} onChange={(e)=>update('unit',e.target.value)} className="w-full rounded-xl border px-3 py-2.5 text-xs" style={inputStyle}><option value="in">in</option><option value="mm">mm</option></select></Field></div>
            <div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Decoration method" note={`Candidate lane methods: ${template.methodExamples.join(', ')}.`}><input value={spec.decorationMethod} onChange={(e)=>update('decorationMethod',e.target.value)} className="w-full rounded-xl border px-3 py-2.5 text-xs" style={inputStyle}/></Field><Field label="Artwork target width / height" note="Optional rectangle-fit math only."><div className="grid grid-cols-2 gap-2"><input type="number" min="0" step="0.01" value={spec.artworkWidth} onChange={(e)=>update('artworkWidth',e.target.value)} className="w-full rounded-xl border px-3 py-2.5 text-xs" style={inputStyle} placeholder="W"/><input type="number" min="0" step="0.01" value={spec.artworkHeight} onChange={(e)=>update('artworkHeight',e.target.value)} className="w-full rounded-xl border px-3 py-2.5 text-xs" style={inputStyle} placeholder="H"/></div></Field></div>
            <label className="mt-4 flex cursor-pointer items-start gap-3 rounded-2xl border p-4" style={{borderColor:spec.restrictionsReviewed?`${C.green}55`:C.line,background:spec.restrictionsReviewed?`${C.green}0B`:C.panel2}}><input type="checkbox" checked={spec.restrictionsReviewed} onChange={(e)=>update('restrictionsReviewed',e.target.checked)} className="mt-0.5 h-4 w-4"/><span><span className="block text-xs font-black" style={{color:C.cream}}>Restrictions reviewed against the controlled source</span><span className="mt-1 block text-[10px] leading-4" style={{color:C.muted}}>Review acknowledgment only; not supplier, artwork, regulatory or production approval.</span></span></label>
            <div className="mt-4"><Field label="Restriction / boundary notes"><textarea value={spec.restrictionNotes} onChange={(e)=>update('restrictionNotes',e.target.value)} rows={3} className="w-full resize-y rounded-xl border px-3 py-2.5 text-xs" style={inputStyle}/></Field></div>
            <div className="mt-5 flex flex-wrap gap-2"><button type="button" onClick={save} className="inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-xs font-black" style={{background:C.green,color:'#071710'}}><Save className="h-4 w-4"/>Save session declaration</button><button type="button" onClick={reset} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-xs font-black" style={{borderColor:C.line,color:C.cream}}><RotateCcw className="h-4 w-4"/>Reset</button></div>{message&&<div className="mt-4 rounded-2xl border px-4 py-3 text-xs leading-5" style={{borderColor:C.line,background:C.panel2,color:C.muted}} aria-live="polite">{message}</div>}
          </section>
          <section className="rounded-3xl border p-5" style={{background:C.panel,borderColor:C.line}}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-black">Product-specific validation preview</h2><Pill tone={binding.imprint.fit.status==='WITHIN_DECLARED_AREA'?'good':'warn'}>{binding.imprint.fit.label}</Pill></div><div className="mt-4"><ConceptVisual concept={concept} markScale={markScale} conceptLabel="Product-specific validation concept"/></div><p className="mt-3 text-[10px] leading-4" style={{color:C.muted}}>Silhouette and mark position remain conceptual. Exact photography, imprint coordinates, geometry, seam boundaries, method tolerances and supplier proofing remain separate validation work.</p></section>
        </section>

        <aside className="space-y-5">
          <section className="rounded-3xl border p-5" style={{background:C.panel,borderColor:C.line}}><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5" style={{color:binding.status==='PRODUCT_SPEC_READY_FOR_HUMAN_VALIDATION'?C.green:C.gold}}/><div><div className="text-[10px] font-black uppercase tracking-[.12em]" style={{color:C.muted}}>Combined gate</div><h2 className="mt-1 text-lg font-black break-words">{binding.status}</h2></div></div><div className="mt-4 grid grid-cols-2 gap-3"><Gate label="Provider" pass={binding.checks.providerEligible} detail={binding.checks.providerEligible?'Eligible projection':'Projection required'}/><Gate label="Concept" pass={binding.checks.conceptMatch} detail={binding.checks.conceptMatch?concept.id:'Mismatch'}/><Gate label="Product ref" pass={binding.checks.productMatch} detail={binding.checks.productMatch?spec.productRef:'Mismatch'}/><Gate label="Revision" pass={binding.checks.sourceRevisionMatch} detail={binding.checks.sourceRevisionMatch?spec.sourceDate:'Mismatch'}/><Gate label="Source" pass={binding.checks.sourceLabelMatch} detail={binding.checks.sourceLabelMatch?spec.sourceLabel:'Mismatch'}/><Gate label="Imprint spec" pass={binding.checks.imprintComplete} detail={`${binding.imprint.score}% declared`}/></div>{binding.blockers.length>0&&<div className="mt-4 flex flex-wrap gap-2">{binding.blockers.map((x)=><Pill key={x} tone="warn">{x}</Pill>)}</div>}</section>
          <section className="rounded-3xl border p-5" style={{borderColor:binding.packet?`${C.green}55`:C.line,background:binding.packet?`${C.green}08`:C.panel2}}><h2 className="text-sm font-black">Human-validation packet</h2>{binding.packet?<div className="mt-4 space-y-2 text-xs leading-5"><div><span style={{color:C.muted}}>Product:</span> <b>{binding.packet.productName}</b></div><div><span style={{color:C.muted}}>Record:</span> <b>{binding.packet.providerRecordId}</b></div><div><span style={{color:C.muted}}>Placement:</span> <b>{binding.packet.imprint.placement}</b></div><div><span style={{color:C.muted}}>Declared area:</span> <b>{binding.packet.imprint.width} × {binding.packet.imprint.height} {binding.packet.imprint.unit}</b></div><div><span style={{color:C.muted}}>Method:</span> <b>{binding.packet.imprint.decorationMethod}</b></div><div className="mt-3 rounded-2xl border p-3 text-[10px] leading-4" style={{borderColor:`${C.gold}44`,color:C.muted}}>{binding.packet.nextAction}</div></div>:<p className="mt-3 text-xs leading-5" style={{color:C.muted}}>No packet is emitted until the provider projection is eligible, exact identities match, and all seven imprint declaration gates are complete.</p>}</section>
          <section className="rounded-3xl border p-5" style={{borderColor:`${C.gold}44`,background:`${C.gold}07`}}><div className="flex items-start gap-3"><TriangleAlert className="mt-0.5 h-5 w-5" style={{color:C.gold}}/><div><div className="text-sm font-black" style={{color:C.gold}}>Authority boundary</div><p className="mt-1 text-xs leading-5" style={{color:C.muted}}>A green packet remains <b style={{color:C.cream}}>READY_FOR_HUMAN_VALIDATION_ONLY</b>. It cannot approve art or proof, quote price, promise inventory/delivery, place an order, contact anyone or start production.</p></div></div></section>
          <div className="flex flex-wrap gap-2"><Link href={`/swagr/virtual/readiness?concept=${encodeURIComponent(concept.id)}`} className="inline-flex rounded-xl border px-3.5 py-2.5 text-xs font-black" style={{borderColor:C.line,color:C.cream}}>Base imprint gate →</Link><Link href="/swagr/data" className="inline-flex rounded-xl border px-3.5 py-2.5 text-xs font-black" style={{borderColor:C.line,color:C.purpleLt}}>Provider gate →</Link></div>
        </aside>
      </section>
    </div>
  </main>;
}
